baseURL = "https://shiveenp.com"
languageCode = "en-us"
theme = "hello-friend"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"

  # "light" or "dark"
  defaultTheme = "light"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 2

  # Show reading time in minutes for posts
  showReadingTime = true

  Comments = true

[languages]
  [languages.en]
    title = "Shiveen Pandita"
    subtitle = "Software engineer based in Sydney. Passionate about travel, landscape photography and open source"
    keywords = "Shiveen,Pandita,Personal,Blog,Software,Programming,Photos"
    copyright = "Â© 2019 - 2020 Shiveen Pandita | CC BY-NC 4.0"
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"
    # leave empty to disable, enter display text to enable
    # lastModDisplay = ""

    [languages.en.params.logo]
      logoText = "Shiveen Pandita"
      logoHomeLink = "/"
    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "uses"
        name = "Uses"
        url = "/uses"

[markup.goldmark.renderer]
unsafe= true